#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

export RUN_ID=${RUN_ID:-phase9-$(date -u +%Y%m%dT%H%M%SZ)}

: "${ASTRAD_BG_IO_THROTTLE_ENABLED:=true}"
: "${ASTRAD_BG_IO_TOKENS_PER_SEC:=8192}"
: "${ASTRAD_BG_IO_BURST_TOKENS:=16384}"
: "${ASTRAD_BG_IO_SQE_THROTTLE_ENABLED:=true}"
: "${ASTRAD_BG_IO_SQE_TOKENS_PER_SEC:=1024}"
: "${ASTRAD_BG_IO_SQE_BURST:=2048}"
: "${ASTRAD_BG_IO_MIN_CHUNK_BYTES:=262144}"
: "${ASTRAD_BG_IO_MAX_CHUNK_BYTES:=262144}"
: "${ASTRAD_LSM_MAX_L0_FILES:=8}"
: "${ASTRAD_LSM_STALL_AT_FILES:=5}"
: "${ASTRAD_LSM_STALL_MAX_DELAY_MS:=200}"
: "${ASTRAD_LSM_REJECT_AFTER_MS:=800}"
: "${ASTRAD_LSM_REJECT_EXTRA_FILES:=1}"
: "${ASTRAD_LSM_SYNTH_FILE_BYTES:=8388608}"
: "${ASTRAD_LSM_DELAY_BAND_L0_5_MS:=1}"
: "${ASTRAD_LSM_DELAY_BAND_L0_6_MS:=5}"
: "${ASTRAD_LSM_DELAY_BAND_L0_7_MS:=20}"
: "${ASTRAD_LIST_PREFIX_FILTER_ENABLED:=true}"
: "${ASTRAD_LIST_REVISION_FILTER_ENABLED:=true}"
: "${ASTRAD_LIST_PREFETCH_ENABLED:=true}"
: "${ASTRAD_LIST_PREFETCH_PAGES:=2}"
: "${ASTRAD_LIST_PREFETCH_CACHE_ENTRIES:=4096}"
: "${ASTRAD_READ_ISOLATION_ENABLED:=true}"
: "${PHASE9_KUBE_MAX_MUTATING_REQUESTS_INFLIGHT:=1000}"
: "${PHASE9_KUBE_MAX_REQUESTS_INFLIGHT:=3000}"
: "${PHASE9_KUBE_DISABLE_APF:=true}"
: "${PHASE9_KUBECONFIG_QPS:=1000}"
: "${PHASE9_KUBECONFIG_BURST:=2000}"
: "${PHASE6_K3S_NODE_CIDR_MASK_IPV4:=16}"
: "${PHASE6_ASTRA_MEM_LIMIT:=1024m}"
: "${PHASE6_ASTRA_NODE_IOPS:=500}"
: "${PHASE6_ASTRA_NODE_BPS:=20971520}"
: "${PHASE9_DISABLE_TIERING_FOR_K3S:=true}"
: "${PHASE9_TELEMETRY_WARMUP_SECS:=90}"
: "${PHASE9_ADAPTIVE_IOWAIT_ENABLED:=true}"
: "${PHASE9_ADAPTIVE_IOWAIT_TARGET:=8}"
: "${PHASE9_ADAPTIVE_IOWAIT_MAX:=12}"
: "${PHASE9_ADAPTIVE_MIN_SLEEP_MS:=0}"
: "${PHASE9_ADAPTIVE_MAX_SLEEP_MS:=250}"
: "${PHASE9_ADAPTIVE_STEP_MS:=25}"
: "${PHASE9_POD_MANIFEST_CHUNK_MIN:=250}"
: "${PHASE9_POD_MANIFEST_CHUNK_MAX:=2000}"
: "${PHASE9_CONFIGMAP_CHUNK_SIZE:=500}"
: "${PHASE9_CONTROLLER_KUBE_API_QPS:=400}"
: "${PHASE9_CONTROLLER_KUBE_API_BURST:=800}"
: "${PHASE9_CONTROLLER_CONCURRENT_DEPLOYMENT_SYNCS:=240}"
: "${PHASE9_CONTROLLER_CONCURRENT_REPLICASET_SYNCS:=240}"
: "${PHASE9_CONTROLLER_CONCURRENT_STATEFULSET_SYNCS:=120}"
: "${PHASE9_CONTROLLER_CONCURRENT_NAMESPACE_SYNCS:=80}"
: "${PHASE9_INJECTION_PARALLELISM:=128}"
: "${PHASE9_POD_INFLATION_MODE:=manifest}"
: "${PHASE9_HARD_POD_GATE:=false}"

export \
  ASTRAD_BG_IO_THROTTLE_ENABLED \
  ASTRAD_BG_IO_TOKENS_PER_SEC \
  ASTRAD_BG_IO_BURST_TOKENS \
  ASTRAD_BG_IO_SQE_THROTTLE_ENABLED \
  ASTRAD_BG_IO_SQE_TOKENS_PER_SEC \
  ASTRAD_BG_IO_SQE_BURST \
  ASTRAD_BG_IO_MIN_CHUNK_BYTES \
  ASTRAD_BG_IO_MAX_CHUNK_BYTES \
  ASTRAD_LSM_MAX_L0_FILES \
  ASTRAD_LSM_STALL_AT_FILES \
  ASTRAD_LSM_STALL_MAX_DELAY_MS \
  ASTRAD_LSM_REJECT_AFTER_MS \
  ASTRAD_LSM_REJECT_EXTRA_FILES \
  ASTRAD_LSM_SYNTH_FILE_BYTES \
  ASTRAD_LSM_DELAY_BAND_L0_5_MS \
  ASTRAD_LSM_DELAY_BAND_L0_6_MS \
  ASTRAD_LSM_DELAY_BAND_L0_7_MS \
  ASTRAD_LIST_PREFIX_FILTER_ENABLED \
  ASTRAD_LIST_REVISION_FILTER_ENABLED \
  ASTRAD_LIST_PREFETCH_ENABLED \
  ASTRAD_LIST_PREFETCH_PAGES \
  ASTRAD_LIST_PREFETCH_CACHE_ENTRIES \
  ASTRAD_READ_ISOLATION_ENABLED \
  PHASE9_KUBE_MAX_MUTATING_REQUESTS_INFLIGHT \
  PHASE9_KUBE_MAX_REQUESTS_INFLIGHT \
  PHASE9_KUBE_DISABLE_APF \
  PHASE9_KUBECONFIG_QPS \
  PHASE9_KUBECONFIG_BURST \
  PHASE6_K3S_NODE_CIDR_MASK_IPV4 \
  PHASE6_ASTRA_MEM_LIMIT \
  PHASE6_ASTRA_NODE_IOPS \
  PHASE6_ASTRA_NODE_BPS \
  PHASE9_DISABLE_TIERING_FOR_K3S \
  PHASE9_TELEMETRY_WARMUP_SECS \
  PHASE9_ADAPTIVE_IOWAIT_ENABLED \
  PHASE9_ADAPTIVE_IOWAIT_TARGET \
  PHASE9_ADAPTIVE_IOWAIT_MAX \
  PHASE9_ADAPTIVE_MIN_SLEEP_MS \
  PHASE9_ADAPTIVE_MAX_SLEEP_MS \
  PHASE9_ADAPTIVE_STEP_MS \
  PHASE9_POD_MANIFEST_CHUNK_MIN \
  PHASE9_POD_MANIFEST_CHUNK_MAX \
  PHASE9_CONFIGMAP_CHUNK_SIZE \
  PHASE9_CONTROLLER_KUBE_API_QPS \
  PHASE9_CONTROLLER_KUBE_API_BURST \
  PHASE9_CONTROLLER_CONCURRENT_DEPLOYMENT_SYNCS \
  PHASE9_CONTROLLER_CONCURRENT_REPLICASET_SYNCS \
  PHASE9_CONTROLLER_CONCURRENT_STATEFULSET_SYNCS \
  PHASE9_CONTROLLER_CONCURRENT_NAMESPACE_SYNCS \
  PHASE9_INJECTION_PARALLELISM \
  PHASE9_POD_INFLATION_MODE \
  PHASE9_HARD_POD_GATE

# shellcheck source=phase6-common.sh
source "${SCRIPT_DIR}/phase6-common.sh"

phase6_log "phase9 integration run starting run_id=${RUN_ID}"
phase6_log "phase9 knobs: chunk_cap=${ASTRAD_BG_IO_MAX_CHUNK_BYTES} l0_bands=${ASTRAD_LSM_DELAY_BAND_L0_5_MS}/${ASTRAD_LSM_DELAY_BAND_L0_6_MS}/${ASTRAD_LSM_DELAY_BAND_L0_7_MS} read_iso=${ASTRAD_READ_ISOLATION_ENABLED} rev_filter=${ASTRAD_LIST_REVISION_FILTER_ENABLED} tiering_disabled=${PHASE9_DISABLE_TIERING_FOR_K3S} warmup_s=${PHASE9_TELEMETRY_WARMUP_SECS} adaptive_iowait=${PHASE9_ADAPTIVE_IOWAIT_ENABLED} astra_mem_limit=${PHASE6_ASTRA_MEM_LIMIT} astra_iops=${PHASE6_ASTRA_NODE_IOPS}"

"${SCRIPT_DIR}/phase6-run-integration.sh" "$@"

if [ -f "${RUN_DIR}/phase6-k3s-astra-summary.json" ] && [ -f "${RUN_DIR}/phase6-k3s-etcd-summary.json" ]; then
  python3 "${SCRIPT_DIR}/build_phase9_matrix.py" \
    --run-dir "${RUN_DIR}" \
    --out-json "${RUN_DIR}/phase9-k3s-matrix.json" \
    --out-csv "${RUN_DIR}/phase9-k3s-matrix.csv"
fi

python3 - <<'PY' "${RUN_ID}" "${RUN_DIR}"
import json
import pathlib
import sys

run_id = sys.argv[1]
run_dir = pathlib.Path(sys.argv[2])


def load(name):
    p = run_dir / name
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return None

index = {
    "run_id": run_id,
    "run_dir": str(run_dir),
    "phase6_index": load("phase6-run-index.json"),
    "phase9_matrix": load("phase9-k3s-matrix.json"),
    "phase9_matrix_csv": str(run_dir / "phase9-k3s-matrix.csv") if (run_dir / "phase9-k3s-matrix.csv").exists() else None,
}
(run_dir / "phase9-run-index.json").write_text(json.dumps(index, indent=2), encoding="utf-8")
print(json.dumps(index, indent=2))
PY

phase6_log "phase9 integration run complete"
phase6_log "index: ${RUN_DIR}/phase9-run-index.json"
