global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - astra-single-node-alerts.yml

scrape_configs:
  - job_name: astra
    static_configs:
      - targets:
          - astra-node1:9479
          - astra-node2:9479
          - astra-node3:9479
