apiVersion: v1
kind: Secret
metadata:
  name: omni-migration-keycloak
  namespace: sidero
type: Opaque
stringData:
  issuer: https://keycloak.example.net/realms/omni
  client-id: astra-migrator
  client-secret: REPLACE_WITH_ASTRA_MIGRATOR_SECRET
