apiVersion: v1
kind: Service
metadata:
  name: astra-peer
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: astra
  ports:
    - name: client
      port: 2379
      targetPort: client
    - name: raft
      port: 2380
      targetPort: raft
    - name: metrics
      port: 9479
      targetPort: metrics
