apiVersion: v1
kind: Secret
metadata:
  name: astra-oidc
  namespace: sidero
type: Opaque
stringData:
  issuer: https://keycloak.example.net/realms/omni
  jwks-url: https://keycloak.example.net/realms/omni/protocol/openid-connect/certs
  audience: astra
